### ISSUE TITLE
Activity Name missing when importing historic activities

### ISSUE THREAD

**Issue by hirael** [tcgoetz/GarminDB#131]
Hi

I have been a Garmin user since 2014, so i have a large amount of data to import and when importing my historic activities, something happend in 2016 that stopped the Activity Name being imported into the database.  I am currently running GarminDB on Windows the command: "python garmindb_cli.py --activities --download --overwrite --import"  

I have tried re-downloading the activities several times but they always end up with 675 entries with no name.   I have attached the log file and the first Fit file where the import stops.  I can send more Fit file examples if needed.

Any guidance would be appreciated - thank you :)

![image](https://user-images.githubusercontent.com/74510648/127885937-598441d9-affd-43bf-b371-db79647ca8d6.png)

[garmindb.log](https://github.com/tcgoetz/GarminDB/files/6917995/garmindb.log)
[activity_details_1378660053.zip](https://github.com/tcgoetz/GarminDB/files/6918003/activity_details_1378660053.zip)

**Comment by Preliator-code** [comment]
Have you found a solution? For me, I am systematically obliged to delete the "HealthData" folder, and run a 
`garmindb_cli.py --all --download --import --analyze`
 to be able to have the updated descriptions

**Comment by hirael** [comment]
For my historic missing data I used Garmin Export to download and import the files into a CSV file and copied the info over from there.

**Comment by tcgoetz** [comment]
I would guess that activities prior to2016 store the name in a different field and the logic that converts activity JSON to DB would need to handle both fields.

**Comment by hirael** [comment]
From what I could see, "elapsedDuration" was missing in the historic activities....  

This change in import_activities.py worked for me:
```
if self._get_field(json_data, 'elapsedDuration'):
     elapsed_time = fitfile.conversions.secs_to_dt_time(self._get_field(json_data, 'elapsedDuration', int))
 else:
     elapsed_time = fitfile.conversions.secs_to_dt_time(self._get_field(json_data, 'duration', int))
```

and this change for my non-distance based activities ....

` 'distance'                  : distance.kms_or_miles(self.measurement_system) if distance is not None else None,`

I did try to report the changes using a pull request, but not sure I got it right!

**Comment by schroeer** [comment]
I have run into the same problem. The change occured some time between 2016/12/05 and 2016/12/10.

For the older activities, `elapsedDuration` is present in both files `activity_\d*\.json` and `activity_details_\d*\.json`. However, in `activity_\d*\.json` the value is `null`. The value in `activity_details_\d*\.json` is correct.

This currently makes [this line](https://github.com/tcgoetz/GarminDB/blob/b13adf0b946c73450d17555237b5507473964a95/garmindb/garmin_json_data.py#L58) fail with `TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'`, as reported in the log.

I believe that there should a check for the value being numerical. I am not sure if additional measures are required to make sure that ultimately the correct value from the details file is recorded in the db. (I see that both files are parsed for these values one after another.) I am using the release version and so can't test right now.

**Comment by schroeer** [comment]
I have run into the same problem. The change occured some time between 2016/12/05 and 2016/12/10.

For the older activities, `elapsedDuration` is present in both files `activity_\d*\.json` and `activity_details_\d*\.json`. However, in `activity_\d*\.json` the value is `null`. The value in `activity_details_\d*\.json` is correct.

This currently makes [this line](https://github.com/tcgoetz/GarminDB/blob/b13adf0b946c73450d17555237b5507473964a95/garmindb/garmin_json_data.py#L58) fail with `TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'` when parsing the summary file, as reported in the log. This prevents those fields that are only extracted from the summary file [(here)](https://github.com/tcgoetz/GarminDB/blob/b13adf0b946c73450d17555237b5507473964a95/garmindb/garmin_json_data.py#L198-L203) from being recorded. Remarkably, the correct value for `elapsed_time` from the details file is already currently written to the database, because it belongs to the fields that are extracted from both files [(here).](https://github.com/tcgoetz/GarminDB/blob/b13adf0b946c73450d17555237b5507473964a95/garmindb/garmin_json_data.py#L57-L80)

So I believe that a check for the value being numerical should be sufficient.

**Comment by tcgoetz** [comment]
@schroeer can you propose the change in a pull request?

**Comment by schroeer** [comment]
I am using the release version and currently don't have a suitable development platform. Consequently, I am able to propose this very simple change but I am not able to test it.

**Comment by schroeer** [comment]
I have patched my local installation and that works as intended.
